### ISSUE TITLE
problem install node-pty

### ISSUE THREAD

**Issue by ramagansid1337** [tegal1337/SubFinder-Web#1]
ini knp ri?
![Screenshot_1](https://github.com/tegal1337/SubFinder-Web/assets/137116400/a091f42f-d559-455b-a697-a3f5e37e3b12)

**Comment by fdciabdul** [comment]
> ini knp ri? ![Screenshot_1](https://user-images.githubusercontent.com/137116400/247814244-a091f42f-d559-455b-a697-a3f5e37e3b12.png)

pake `yarn`

**Comment by ramagansid1337** [comment]
kalo ini gmna ri?
udah install yarn~>yarn add node-pty~> trs npm install lgi error

![Screenshot_2](https://github.com/tegal1337/SubFinder-Web/assets/137116400/0884716c-0d09-494e-9731-5beaf5f4d14f)

**Comment by fdciabdul** [comment]
kalau udah pake yarn , gausah npm install lagi 

tinggal npm start aja
